<?php
/**
 * Implements hook_node_info()
 */
function demotest_node_info() {
    return [
        'demotest' => [
            'name' => t('By Line'),
            'base' => 'demotest',
            'description' => t('Demo Test By Line Custom Type'),
            'has_title' => true,
            'title_label' => t('By Line title'),
        ],
    ];
}

/**
 * Implements hook_form()
 */
function demotest_form($node, $form_state) {
    return node_content_form($node, $form_state);
}

/**
 * Implements hook_theme().
 */
function demotest_theme() {
  return [
    'demotest' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_theme_registry_alter
 */
function demotest_theme_registry_alter(&$theme_registry) {
  $theme_registry['node']['path'] = drupal_get_path('module', 'demotest') . '/templates';
}

/**
 * Implements hook_heme_registry_alter
 */
function demotest_preprocess_node(&$variables){
    if (isset($variables['node'])) $variables['content_type'] = $variables['type'];
}